return {
    "nvim-treesitter/nvim-treesitter",
    lazy = false,
    branch = "main",
    build = ":TSUpdate",
    config = function ()
      require("nvim-treesitter").install({
        "asm",
        "astro",
        "bash",
        "c",
        "c_sharp",
        "cpp",
        "css",
        "dart",
        "dot",
        "html",
        "java",
        "javascript",
        "json",
        "kotlin",
        "lua",
        "markdown",
        "markdown_inline",
        "odin",
        "python",
        "rust",
        "sql",
        "typescript",
        "vim",
        "vimdoc",
        "zig"
      })
    end,
}
